[workspace]
members = [
    "crates/api-server",
    "crates/database",
    "crates/frontend",
    "crates/common",
    "crates/config",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
