[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { path = "../config" }
diesel = { version = "2.0", features = ["sqlite", "r2d2"] }
dotenv = "0.15"

[lib]
path = "src/lib.rs"
