apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-bittorrent-api
  labels:
    app: stremio-bittorrent-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stremio-bittorrent-api
  template:
    metadata:
      labels:
        app: stremio-bittorrent-api
    spec:
      containers:
      - name: stremio-bittorrent-api
        image: stremio-bittorrent-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: RUST_LOG
          value: "info"
        - name: DATABASE_PATH
          value: "/app/data/stremio.db"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: stremio-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: stremio-bittorrent-api-service
spec:
  selector:
    app: stremio-bittorrent-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stremio-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
